name: Publish NuGet Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Download NuGet Packages from Release
        run: |
          Write-Host "GITHUB_REF: '$($env:GITHUB_REF)'"
          $prefix = "refs/tags/"
          $name = $($env:GITHUB_REF).Substring($prefix.Length)
          Write-Host "name: '$name'"
          gh release download $name --repo siemens/opc-ua-pubsub-dotnet --pattern '*.nupkg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "*.nupkg" --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

